<SaveWindow>
    name: "save"

    BoxLayout:
        orientation: 'vertical'
        rows: 2

        MDLabel:
            id: text_label
            halign: 'center'
            valign: 'top'
            size_hint_y: None
            padding_y: 15

        Button:
            text: 'Сохранить текущую игру'
            size_hint_y: None
            height: '48dp'
            width: '420dp'
            #Обработчик
            on_release:
                root.saveFile()